### ISSUE TITLE
Surface density values at specific radii 

### ISSUE THREAD

**Issue by kh-kr** [mgieles/limepy#17]
Hi,

I am using the function below to fit Kings model to my data

def minloglike(par, Rdat):
    # par is an array with parameters: W0 and rh, create a model with parameters par
    m = limepy(par[0], 1, M=1, rh=par[1], project=True) 
    # Return the minus log likelihood, note that the model is normalised to M=1 above
    return -sum(np.log(np.interp(Rdat, m.R, m.Sigma, right=1e-9)))

   x0 = [5,6 ] # Starting values
    res = fmin(minloglike, x0, args=(R,))                 ...(1)

where R is my data (distances of annular regions from the cluster center):

[ 0.81300259  1.63805286  2.45644916  3.27178108  4.11186796  4.89757079
  5.72721537  6.56890879  7.38292991  8.22157585  9.03506765  9.83184631
 10.62514494 11.45452636 12.34412786 13.15342855 13.99589347 14.83267229], 

but when I pass this array to eq (1), it gives me an error "IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed"

The array is of numpy array (same as given in "01_sample_and_fit_limepy" example file). I need to pass this array to estimate model sigma values at these distances to calculate reduced chi square values.

Kindly regarding the same.

Thank you for your time!

best regards,
Khushboo

**Comment by mgieles** [comment]
This happens because a negative phi0 was provided to limepy by fmin. There is now a RaiseError if this happens, but careful with fmin, because rh can also go negative, you can not provide a bound in fmin.
