### ISSUE TITLE
raj error with spes.sample

### ISSUE THREAD

**Issue by webbjj** [mgieles/limepy#3]
Hi Mark et al.

I have been trying to generate a sample of points for the clusters with SPES model fits presented in de Boer et al 2019. Getting the model itself works, but trying to generate individual stars returns an error (sample code and error copied below). It states that spes models do not have an attribute called raj, which as far as I can tell from the limepy models is for anisotropic models. Is raj supposed to be specified somehow? Or has sample not yet been applied to spes models?

Thanks - Jeremy

Sample Code:
import limpy
from limepy import spes,sample

model=spes(phi0=W_pe,B=10.0**log1minB_pe,eta=eta_pe,fpe=10.0**log_fpe,M=M_pe,rt=rt_pe)
data=sample(model,N=N)

Error:
data=sample(model,N=N)
  File "/usr/local/lib/python3.6/site-packages/limepy-0.1.0-py3.6.egg/limepy/sample.py", line 30, in __init__
    self._set_params_and_init(mod, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/limepy-0.1.0-py3.6.egg/limepy/sample.py", line 58, in _set_params_and_init
    self.ani = True if min(mod.raj)/mod.rt < 3 else False
AttributeError: 'spes' object has no attribute 'raj'

**Comment by mgieles** [comment]
Thanks for pointing this out: SPES models are isotropic and there is no discrete sampling implemented. SPES are not in virial equilibrium without a reflecting boundary (See section 2.1 in Claydon et al. 2019), hence you may not want to use them as ICs for N-body models. 

A warning is implemented when trying to sample from SPES models.
