### ISSUE TITLE
ImportError: cannot import name 'limepy' from 'limepy'

### ISSUE THREAD

**Issue by nbanik** [mgieles/limepy#6]
I installed limepy via pip and it seems to have installed properly 

> Collecting limepy
  Using cached https://files.pythonhosted.org/packages/4a/be/45a78bbef395e45be81e40f7be9ff69a4b45c26cb5fd98f2abcf0caf6110/limepy-0.1.3-py3-none-any.whl
Requirement already satisfied: xmltodict in /home/nil/anaconda3/lib/python3.7/site-packages (from limepy) (0.12.0)
Requirement already satisfied: numpy in /home/nil/anaconda3/lib/python3.7/site-packages (from limepy) (1.17.2)
Requirement already satisfied: requests in /home/nil/anaconda3/lib/python3.7/site-packages (from limepy) (2.22.0)
Requirement already satisfied: pandas in /home/nil/anaconda3/lib/python3.7/site-packages (from limepy) (0.25.1)
Requirement already satisfied: idna<2.9,>=2.5 in /home/nil/anaconda3/lib/python3.7/site-packages (from requests->limepy) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/nil/anaconda3/lib/python3.7/site-packages (from requests->limepy) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/nil/anaconda3/lib/python3.7/site-packages (from requests->limepy) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/nil/anaconda3/lib/python3.7/site-packages (from requests->limepy) (2019.9.11)
Requirement already satisfied: pytz>=2017.2 in /home/nil/anaconda3/lib/python3.7/site-packages (from pandas->limepy) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/nil/anaconda3/lib/python3.7/site-packages (from pandas->limepy) (2.8.0)
Requirement already satisfied: six>=1.5 in /home/nil/anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->limepy) (1.12.0)
Installing collected packages: limepy
Successfully installed limepy-0.1.3

But when I run 
    from limepy import limepy 

I get the error : 

> ImportError: cannot import name 'limepy' from 'limepy' (/home/nil/anaconda3/lib/python3.7/site-packages/limepy/__init__.py) 

Simply running `import limepy` doesn't return any error.

**Comment by mgieles** [comment]
There is a name clash with another package, you can still install with pip:

pip install git+https://github.com/mgieles/limepy

I updated the instructions for installation.

Mark

**Comment by nbanik** [comment]
Awesome! Thanks Mark. 

Nil
