### ISSUE TITLE
Error calling spes.df

### ISSUE THREAD

**Issue by webbjj** [mgieles/limepy#8]
Hi again Mark

I have been playing around more with the SPES models, and was hoping to be able to call the distribution function for a given r,v. However I am getting an error.

test=spes(phi0 = 1.5, B = 0.5, eta = 0.4, M = 1.2e5, rh=3.)
test.df(1,1)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-131-f2d486b8513f> in <module>
      2 v=np.ones(10)
      3 
----> 4 test.df(r,v)

/usr/local/lib/python3.7/site-packages/limepy-0.1.0-py3.7.egg/limepy/spes.py in df(self, *arg)
    804             raise ValueError("Error: df needs 2, 3, 4 or 7 arguments")
    805 
--> 806         if (len(arg)<=3) and (self.ra<self.ramax):
    807             raise ValueError("Error: model is anisotropy, more input needed")
    808 

AttributeError: 'spes' object has no attribute 'ra'

It looks like self.ra and self.ramax are not defined in SPES models. There is a point later in def DF where self.raj is called and I don't think that is defined either. Any help you can provide would be greatly appreciated.

Jeremy

**Comment by mgieles** [comment]
hi Jeremy

The DF computation was not yet implemented and an old piece of LIMEPY code was executed in your example. 

The DF (eq 3 from Claydon+ 2019) is now implemented in spes.py and can be called in the way you used in your example. It works for scalars and arrays.

I tested it with a double integral over r and v and I retrieved the total mass.

Cheers

**Comment by mgieles** [comment]
Done!
Let me know if you have any problems.

Cheers
